### ISSUE TITLE
update to latest game version?

### ISSUE THREAD

**Issue by PaloAlo** [ColdSpirit0/ValheimGammaMod#1]
hi, it seems to be causing issues in a dedicated server environment. players that have the mod installed cannot connect to the server.

it might need to be rebuilt with the latest game version.

**Comment by ColdSpirit0** [comment]
I tested the mod with the latest version of Valheim and vanilla dedicated server, and after installing the mod via Thunderstore Manager, everything works fine.

If you still have problems - please send more info
